// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProjectPhoto = "project_photos"

// ProjectPhoto mapped from table <project_photos>
type ProjectPhoto struct {
	ID        string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	RootID    string    `gorm:"column:root_id" json:"root_id"`
	URL       string    `gorm:"column:url;not null" json:"url"`
	CreatedAt time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
}

// TableName ProjectPhoto's table name
func (*ProjectPhoto) TableName() string {
	return TableNameProjectPhoto
}
