// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameService = "services"

// Service mapped from table <services>
type Service struct {
	ID          string  `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Name        string  `gorm:"column:name" json:"name"`
	Description string  `gorm:"column:description" json:"description"`
	Price       float64 `gorm:"column:price" json:"price"`
	ImageURL    string  `gorm:"column:image_url" json:"image_url"`
	IsActive    bool    `gorm:"column:is_active;not null;default:true" json:"is_active"`
}

// TableName Service's table name
func (*Service) TableName() string {
	return TableNameService
}
