version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  minio:
    container_name: minio-comfort-park
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    volumes:
      - minio_data:/data
    ports:
      - "9090:9000"
      - "9091:9001"
    command: server --console-address ":9001" /data
    networks:
      - backend-network

volumes:
  postgres_data:
  minio_data:

networks:
  backend-network:
