// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProject = "projects"

// Project mapped from table <projects>
type Project struct {
	ID          string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Name        string    `gorm:"column:name" json:"name"`
	Description string    `gorm:"column:description" json:"description"`
	CreatedAt   time.Time `gorm:"column:created_at;default:now()" json:"created_at"`

	ProjectPhoto        	[]ProjectPhoto       `gorm:"foreignKey:RootID"`
	ProjectReview 			[]ProjectReview	     `gorm:"foreignKey:RootID"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
