// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDictsBuildingCategory = "dicts_building_category"

// DictsBuildingCategory mapped from table <dicts_building_category>
type DictsBuildingCategory struct {
	ID       string `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	Code     string `gorm:"column:code;not null" json:"code"`
	Name     string `gorm:"column:name" json:"name"`
	IsActive bool   `gorm:"column:is_active;not null;default:true" json:"is_active"`
}

// TableName DictsBuildingCategory's table name
func (*DictsBuildingCategory) TableName() string {
	return TableNameDictsBuildingCategory
}
