// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProjectReview = "project_reviews"

// ProjectReview mapped from table <project_reviews>
type ProjectReview struct {
	ID        string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	RootID    string    `gorm:"column:root_id" json:"root_id"`
	FirstName string    `gorm:"column:first_name" json:"first_name"`
	LastName  string    `gorm:"column:last_name" json:"last_name"`
	Comment   string    `gorm:"column:comment" json:"comment"`
	Photos    string    `gorm:"column:photos" json:"photos"`
	CreatedAt time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
}

// TableName ProjectReview's table name
func (*ProjectReview) TableName() string {
	return TableNameProjectReview
}
